[tool.poetry]
name = "assignment-web-client"
version = "0.1.0"
description = ""
authors = ["Tianxiang Ren <tianxia3@ualberta.ca>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
